/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

/**
 *
 * @author samue
 */
public class MainWindow extends javax.swing.JFrame {

    public Controlador controlador;
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        this.controlador = new Controlador(this);
    }
    
    public void alerta(String mensgem){
        labelAviso.setText(mensgem);
        caixaAviso.setVisible(true);
    }
    
    public void mostraProximoJogador(int jogador){
        labelJogadorAtual.setText(Integer.toString(jogador));
    }
    
    public void zerarCampos(){
        campo1.setText("");
        campo2.setText("");
        campo3.setText("");
        campo4.setText("");
        campo5.setText("");
        campo6.setText("");
        campo7.setText("");
        campo8.setText("");
        campo9.setText("");
        labelJogadorAtual.setText("1");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        caixaAviso = new javax.swing.JDialog();
        novoJogo2 = new javax.swing.JButton();
        labelAviso = new java.awt.Label();
        sair = new javax.swing.JButton();
        novoJogo = new java.awt.Button();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        campo5 = new java.awt.Label();
        campo1 = new java.awt.Label();
        campo2 = new java.awt.Label();
        campo3 = new java.awt.Label();
        campo8 = new java.awt.Label();
        campo9 = new java.awt.Label();
        campo6 = new java.awt.Label();
        campo7 = new java.awt.Label();
        campo4 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        labelJogadorAtual = new javax.swing.JLabel();
        botaoSair = new javax.swing.JButton();

        caixaAviso.setTitle("Aviso");
        caixaAviso.setAlwaysOnTop(true);
        caixaAviso.setForeground(java.awt.Color.gray);
        caixaAviso.setLocation(new java.awt.Point(50, 50));
        caixaAviso.setName("caixaAlerta"); // NOI18N
        caixaAviso.setResizable(false);
        caixaAviso.setSize(new java.awt.Dimension(350, 250));
        caixaAviso.setType(java.awt.Window.Type.POPUP);

        novoJogo2.setText("Novo Jogo");
        novoJogo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                novoJogo2MousePressed(evt);
            }
        });
        novoJogo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoJogo2ActionPerformed(evt);
            }
        });

        labelAviso.setAlignment(java.awt.Label.CENTER);
        labelAviso.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelAviso.setName(""); // NOI18N
        labelAviso.setText("Aviso");

        sair.setText("Sair");
        sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sairMousePressed(evt);
            }
        });

        javax.swing.GroupLayout caixaAvisoLayout = new javax.swing.GroupLayout(caixaAviso.getContentPane());
        caixaAviso.getContentPane().setLayout(caixaAvisoLayout);
        caixaAvisoLayout.setHorizontalGroup(
            caixaAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(caixaAvisoLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(novoJogo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(sair)
                .addGap(63, 63, 63))
            .addComponent(labelAviso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        caixaAvisoLayout.setVerticalGroup(
            caixaAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(caixaAvisoLayout.createSequentialGroup()
                .addComponent(labelAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(caixaAvisoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novoJogo2)
                    .addComponent(sair))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        novoJogo.setActionCommand("novoJogo");
        novoJogo.setLabel("Novo Jogo");
        novoJogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                novoJogoMousePressed(evt);
            }
        });
        novoJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoJogoActionPerformed(evt);
            }
        });

        label1.setText("Jogador 1 - X");

        label2.setText("Jogador 2 - O");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setAlignmentX(0.6F);
        jSeparator1.setAlignmentY(0.6F);
        jSeparator1.setAutoscrolls(true);
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jSeparator1.setMinimumSize(new java.awt.Dimension(50, 20));
        jSeparator1.setName(""); // NOI18N
        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 20));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setAlignmentX(0.6F);
        jSeparator2.setAlignmentY(0.6F);
        jSeparator2.setAutoscrolls(true);
        jSeparator2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jSeparator2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jSeparator2.setMinimumSize(new java.awt.Dimension(50, 20));
        jSeparator2.setName(""); // NOI18N
        jSeparator2.setPreferredSize(new java.awt.Dimension(50, 20));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setAlignmentX(0.6F);
        jSeparator3.setAlignmentY(0.6F);
        jSeparator3.setAutoscrolls(true);
        jSeparator3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jSeparator3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jSeparator3.setMinimumSize(new java.awt.Dimension(50, 20));
        jSeparator3.setName(""); // NOI18N
        jSeparator3.setPreferredSize(new java.awt.Dimension(50, 20));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator4.setAlignmentX(0.6F);
        jSeparator4.setAlignmentY(0.6F);
        jSeparator4.setAutoscrolls(true);
        jSeparator4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jSeparator4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jSeparator4.setMinimumSize(new java.awt.Dimension(50, 20));
        jSeparator4.setName(""); // NOI18N
        jSeparator4.setPreferredSize(new java.awt.Dimension(50, 20));

        campo5.setAlignment(java.awt.Label.CENTER);
        campo5.setFont(new java.awt.Font("Dialog", 1, 52)); // NOI18N
        campo5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campo5MousePressed(evt);
            }
        });

        campo1.setAlignment(java.awt.Label.CENTER);
        campo1.setFont(new java.awt.Font("Dialog", 1, 52)); // NOI18N
        campo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campo1MousePressed(evt);
            }
        });

        campo2.setAlignment(java.awt.Label.CENTER);
        campo2.setFont(new java.awt.Font("Dialog", 1, 52)); // NOI18N
        campo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campo2MousePressed(evt);
            }
        });

        campo3.setAlignment(java.awt.Label.CENTER);
        campo3.setFont(new java.awt.Font("Dialog", 1, 52)); // NOI18N
        campo3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campo3MousePressed(evt);
            }
        });

        campo8.setAlignment(java.awt.Label.CENTER);
        campo8.setFont(new java.awt.Font("Dialog", 1, 52)); // NOI18N
        campo8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campo8MousePressed(evt);
            }
        });

        campo9.setAlignment(java.awt.Label.CENTER);
        campo9.setFont(new java.awt.Font("Dialog", 1, 52)); // NOI18N
        campo9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campo9MousePressed(evt);
            }
        });

        campo6.setAlignment(java.awt.Label.CENTER);
        campo6.setFont(new java.awt.Font("Dialog", 1, 52)); // NOI18N
        campo6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campo6MousePressed(evt);
            }
        });

        campo7.setAlignment(java.awt.Label.CENTER);
        campo7.setFont(new java.awt.Font("Dialog", 1, 52)); // NOI18N
        campo7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campo7MousePressed(evt);
            }
        });

        campo4.setAlignment(java.awt.Label.CENTER);
        campo4.setFont(new java.awt.Font("Dialog", 1, 52)); // NOI18N
        campo4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                campo4MousePressed(evt);
            }
        });

        jLabel1.setText("Agora é a vez do jogador ");

        labelJogadorAtual.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        labelJogadorAtual.setText("1");

        botaoSair.setText("Sair");
        botaoSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botaoSairMousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(campo2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campo5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(campo3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campo6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(campo1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campo4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addComponent(campo7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(campo9, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campo8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(80, 80, 80))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(novoJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelJogadorAtual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoSair)
                .addGap(23, 23, 23))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(78, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(149, 149, 149)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(313, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(268, 268, 268)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(194, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(novoJogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelJogadorAtual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botaoSair))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(campo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campo2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(218, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(87, 87, 87)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void novoJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoJogoActionPerformed

    }//GEN-LAST:event_novoJogoActionPerformed

    private void campo5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo5MousePressed
        int jogador = this.controlador.marcar(1, 1);
        if(jogador == 1){
            campo5.setText("X");
        }else if(jogador == 2){
            campo5.setText("O");
        }
    }//GEN-LAST:event_campo5MousePressed

    private void campo1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo1MousePressed
        int jogador = this.controlador.marcar(0, 0);
        if(jogador == 1){
            campo1.setText("X");
        }else if(jogador == 2){
            campo1.setText("O");
        }
    }//GEN-LAST:event_campo1MousePressed

    private void campo2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo2MousePressed
        int jogador = this.controlador.marcar(1, 0);
        if(jogador == 1){
            campo2.setText("X");
        }else if(jogador == 2){
            campo2.setText("O");
        }
    }//GEN-LAST:event_campo2MousePressed

    private void campo3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo3MousePressed
        int jogador = this.controlador.marcar(2, 0);
        if(jogador == 1){
            campo3.setText("X");
        }else if(jogador == 2){
            campo3.setText("O");
        }
    }//GEN-LAST:event_campo3MousePressed

    private void campo4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo4MousePressed
        int jogador = this.controlador.marcar(0, 1);
        if(jogador == 1){
            campo4.setText("X");
        }else if(jogador == 2){
            campo4.setText("O");
        }
    }//GEN-LAST:event_campo4MousePressed

    private void campo6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo6MousePressed
        int jogador = this.controlador.marcar(2, 1);
        if(jogador == 1){
            campo6.setText("X");
        }else if(jogador == 2){
            campo6.setText("O");
        }
    }//GEN-LAST:event_campo6MousePressed

    private void campo7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo7MousePressed
        int jogador = this.controlador.marcar(0, 2);
        if(jogador == 1){
            campo7.setText("X");
        }else if(jogador == 2){
            campo7.setText("O");
        }
    }//GEN-LAST:event_campo7MousePressed

    private void campo8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo8MousePressed
        int jogador = this.controlador.marcar(1, 2);
        if(jogador == 1){
            campo8.setText("X");
        }else if(jogador == 2){
            campo8.setText("O");
        }
    }//GEN-LAST:event_campo8MousePressed

    private void campo9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campo9MousePressed
        int jogador = this.controlador.marcar(2, 2);
        if(jogador == 1){
            campo9.setText("X");
        }else if(jogador == 2){
            campo9.setText("O");
        }
    }//GEN-LAST:event_campo9MousePressed

    private void novoJogoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_novoJogoMousePressed
        this.controlador.novoJogo();
        this.zerarCampos();
    }//GEN-LAST:event_novoJogoMousePressed

    private void novoJogo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoJogo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novoJogo2ActionPerformed

    private void novoJogo2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_novoJogo2MousePressed
        this.controlador.novoJogo();
        this.zerarCampos();
        caixaAviso.setVisible(false);
    }//GEN-LAST:event_novoJogo2MousePressed

    private void sairMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairMousePressed
        System.exit(0);
    }//GEN-LAST:event_sairMousePressed

    private void botaoSairMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoSairMousePressed
        System.exit(0);
    }//GEN-LAST:event_botaoSairMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSair;
    private javax.swing.JDialog caixaAviso;
    private java.awt.Label campo1;
    private java.awt.Label campo2;
    private java.awt.Label campo3;
    private java.awt.Label campo4;
    private java.awt.Label campo5;
    private java.awt.Label campo6;
    private java.awt.Label campo7;
    private java.awt.Label campo8;
    private java.awt.Label campo9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label labelAviso;
    private javax.swing.JLabel labelJogadorAtual;
    private java.awt.Button novoJogo;
    private javax.swing.JButton novoJogo2;
    private javax.swing.JButton sair;
    // End of variables declaration//GEN-END:variables
}
